/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CupPlate(props) {
  const { nodes, materials } = useGLTF('model/plate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Salad_Plate.geometry} material={materials['Metal Set 01']} />
    </group>
  )
}

useGLTF.preload('model/plate.glb')
