/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alihan (https://sketchfab.com/Dare0)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/direction-arrow-6ef46718c7b242e39fcad7f27ee858a5
title: Direction Arrow
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DirectionArrow(props) {
  const { nodes, materials } = useGLTF('model/direction_arrow.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.02]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[11.48, 8.66, 11.4]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Arrow_Material001_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('model/direction_arrow.glb')
