/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Fork(props) {
  const { nodes, materials } = useGLTF('model/fork.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fork.geometry} material={materials['Metal Set 01']} />
    </group>
  )
}

useGLTF.preload('model/fork.glb')
