/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Hello(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('model/hello.glb')
  const { actions, names } = useAnimations(animations, group)
  useEffect(()=>{
    console.log(actions, names);
    console.log(materials.PBR);
    actions.animation_0.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={10000000000} near={0.01} fov={31.42} position={[97.89, 478.3, -1331.04]} rotation={[3.11, -0.26, 3.13]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PBR} position={[-470.79, 16.19, -9.23]} />
      </group>
    </group>
  )
}

useGLTF.preload('model/hello.glb')
