/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Home(props) {
  const { nodes, materials } = useGLTF('model/home.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[51.11, -3.29, 14.11]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.H_T.geometry} material={materials['Wood Fraxinus']} position={[0, 27.85, 0]}>
          <mesh geometry={nodes.Rounding_1.geometry} material={materials['Wood Fraxinus']} position={[24.13, 0, 0]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.Cap_1_4.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
          <mesh geometry={nodes.Rounding_2.geometry} material={materials['Wood Fraxinus']}>
            <mesh geometry={nodes.Cap_2_4.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.H_L.geometry} material={materials['Wood Fraxinus']}>
          <mesh geometry={nodes.Rounding_1_1.geometry} material={materials['Wood Fraxinus']} position={[24.13, 0, 0]}>
            <mesh geometry={nodes.Cap_1_5.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_1.geometry} material={materials['Wood Fraxinus']}>
            <mesh geometry={nodes.Cap_2_5.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.F_V_L.geometry} material={materials['Wood Fraxinus']} position={[24.13, 0, 0]}>
          <mesh geometry={nodes.Rounding_1_2.geometry} material={materials['Wood Fraxinus']}>
            <mesh geometry={nodes.Cap_1_6.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_2.geometry} material={materials['Wood Fraxinus']} position={[0, 27.85, 0]}>
            <mesh geometry={nodes.Cap_2_6.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.F_V_P.geometry} material={materials['Wood Fraxinus']}>
          <mesh geometry={nodes.Rounding_1_3.geometry} material={materials['Wood Fraxinus']}>
            <mesh geometry={nodes.Cap_1_7.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_3.geometry} material={materials['Wood Fraxinus']} position={[0, 27.85, 0]}>
            <mesh geometry={nodes.Cap_2_7.geometry} material={materials['Wood Fraxinus']} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.Frame_plinth.geometry} material={materials.Plinth} position={[1.49, 0, 0]}>
          <mesh geometry={nodes.Cap_1.geometry} material={materials.Plinth} />
          <mesh geometry={nodes.Cap_2.geometry} material={materials.Plinth} />
        </mesh>
        <group position={[0.54, 0.54, 1.45]}>
          <group position={[0.11, 0, 0]}>
            <group position={[11.42, 13.27, -0.48]}>
              <mesh geometry={nodes.hor_divider_cube_0.geometry} material={materials.Dividers} position={[0, -6.08, 0]} />
              <mesh geometry={nodes.hor_divider_cube_1.geometry} material={materials.Dividers} position={[0, 6.08, 0]} />
            </group>
            <group position={[11.42, 13.27, -0.48]}>
              <mesh geometry={nodes.ver_divider_cube_0.geometry} material={materials.Dividers} position={[-5.15, 0, 0]} />
              <mesh geometry={nodes.ver_divider_cube_1.geometry} material={materials.Dividers} position={[5.15, 0, 0]} />
            </group>
            <mesh geometry={nodes.Glass_inner.geometry} material={materials.Glass} position={[11.42, 13.27, -0.45]} />
            <mesh geometry={nodes.Glass_outer.geometry} material={materials.Glass} position={[11.42, 13.27, -1.01]} />
            <mesh geometry={nodes.Handle.geometry} material={materials.Handle} position={[22.18, 13.27, 0.19]} rotation={[-Math.PI, 0, -Math.PI]}>
            </mesh>
            <mesh geometry={nodes.Metal.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Silicon.geometry} material={materials.Silicon} />
            <mesh geometry={nodes.Gasket.geometry} material={materials.Gasket} />
            <group position={[0, 0, -0.11]}>
              <mesh geometry={nodes.B_H.geometry} material={materials['Wood Fraxinus']}>
                <mesh geometry={nodes.Rounding_1_4.geometry} material={materials['Wood Fraxinus']}>
                  <mesh geometry={nodes.Cap_1_8.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
                <mesh geometry={nodes.Rounding_2_4.geometry} material={materials['Wood Fraxinus']} position={[22.83, 0, 0]}>
                  <mesh geometry={nodes.Cap_2_8.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
              </mesh>
              <mesh geometry={nodes.T_H.geometry} material={materials['Wood Fraxinus']} position={[0, 26.55, 0]}>
                <mesh geometry={nodes.Rounding_1_5.geometry} material={materials['Wood Fraxinus']}>
                  <mesh geometry={nodes.Cap_1_9.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
                <mesh geometry={nodes.Rounding_2_5.geometry} material={materials['Wood Fraxinus']} position={[22.83, 0, 0]}>
                  <mesh geometry={nodes.Cap_2_9.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
              </mesh>
            </group>
            <group position={[0, 0, -0.11]}>
              <mesh geometry={nodes.V_R.geometry} material={materials['Wood Fraxinus']}>
                <mesh geometry={nodes.Rounding_1_6.geometry} material={materials['Wood Fraxinus']}>
                  <mesh geometry={nodes.Cap_1_10.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
                <mesh geometry={nodes.Rounding_2_6.geometry} material={materials['Wood Fraxinus']} position={[0, 26.55, 0]}>
                  <mesh geometry={nodes.Cap_2_10.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
              </mesh>
              <mesh geometry={nodes.V_L.geometry} material={materials['Wood Fraxinus']} position={[22.83, 0, 0]}>
                <mesh geometry={nodes.Rounding_1_7.geometry} material={materials['Wood Fraxinus']}>
                  <mesh geometry={nodes.Cap_1_11.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
                <mesh geometry={nodes.Rounding_2_7.geometry} material={materials['Wood Fraxinus']} position={[0, 26.55, 0]}>
                  <mesh geometry={nodes.Cap_2_11.geometry} material={materials['Wood Fraxinus']} />
                </mesh>
              </mesh>
            </group>
            <mesh geometry={nodes.Front_fillet.geometry} material={materials['Wood Fraxinus']} />
            <mesh geometry={nodes.Wing_Plinth.geometry} material={materials.Plinth} position={[1.39, 1, -0.71]}>
              <mesh geometry={nodes.Cap_1_1.geometry} material={materials.Plinth} />
              <mesh geometry={nodes.Cap_2_1.geometry} material={materials.Plinth} />
            </mesh>
          </group>
          <group position={[0, 0.93, 0]}>
            <mesh geometry={nodes.Hinge_Instance.geometry} material={materials.Hinges} position={[0, 24.69, 0]} />
            <mesh geometry={nodes.Hinge.geometry} material={materials.Hinges} />
          </group>
        </group>
      </group>
      <group position={[0, -1.4, 0]}>
        <mesh geometry={nodes.Cube1.geometry} material={materials.PBR} position={[0, 46.08, 0]} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['PBR.2']} position={[50.85, -15.7, -0.22]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['PBR.1']} />
    </group>
  )
}

useGLTF.preload('model/home.glb')
