/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export function New_bird(props) {
  const ref = useRef();
  const { nodes, materials } = useGLTF('model/new_bird.gltf')
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.x = -Math.PI / 1.75 + Math.cos(t / 4) / 8
    ref.current.rotation.y = Math.sin(t / 4) / 8
    ref.current.rotation.z = ref.current.rotation.z+(1 + Math.sin(t / 1.5)) / 20
    ref.current.position.y = (1 + Math.sin(t / 1.5)) / 10
  })
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[38.04, 217.32, -57.09]}>
        <group position={[-10.27, -27.03, -0.18]}>
          <group position={[7.23, 179.17, -62.19]} rotation={[0, 0, -0.9]}>
            <mesh geometry={nodes.Cube_1.geometry} material={materials['White Glossy']} />
          </group>
        </group>
        <group position={[-10.27, -50.27, -8.25]}>
          <mesh geometry={nodes.Eye_2.geometry} material={nodes.Eye_2.material} position={[54.06, 179.84, 1.21]} scale={[0.52, 0.95, 1]} />
        </group>
        <group position={[-10.27, -26.35, -0.18]}>
          <mesh geometry={nodes.Wing.geometry} material={materials['White Glossy']} position={[88.51, -56.44, 76.89]} />
        </group>
        <group position={[-10.27, -26.35, -0.18]}>
          <mesh geometry={nodes.Pigeon_1.geometry} material={materials['Mat.1']} position={[0, 51.3, 0]} />
        </group>
        <group position={[-10.27, -26.35, -0.18]}>
          <mesh geometry={nodes.Peak.geometry} material={nodes.Peak.material} position={[0, 154.46, -56.11]} />
        </group>
        <mesh geometry={nodes.Eye_1.geometry} material={materials['Plastic Black - Glossy']} position={[51.33, 129.57, -7.03]} scale={[0.72, 1.02, 1]} />
      </group>

      
      <mesh geometry={nodes.Eye.geometry} material={materials['Plastic Black - Glossy']} position={[-30.63, 346.89, -64.13]} scale={[0.72, 1.02, 1]} />
    </group>
  )
}

useGLTF.preload('model/new_bird.gltf')
