/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Newbook(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('model/newbook.glb')
  const { actions, names } = useAnimations(animations, group);
  
  useEffect(()=>{
    actions[names[0]].play()
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Magazine_-_Thin">
          <group name="Cover" position={[0, 0, -12.19]} rotation={[0, 1.57, 0]}>
            <mesh name="Cover_1" geometry={nodes.Cover_1.geometry} material={materials.Plain} />
          </group>
          <group name="Staples" position={[-10.27, 0, 2.67]} rotation={[0, 1.57, 0]}>
            <mesh name="Staple_02" geometry={nodes.Staple_02.geometry} material={materials.Staples} position={[-9.83, 0, 0]} />
            <mesh name="Staple_01" geometry={nodes.Staple_01.geometry} material={materials.Staples} position={[9.83, 0, 0]} />
          </group>
          <mesh name="Content" geometry={nodes.Content.geometry} material={materials.book} position={[0, 0, -12.19]} rotation={[0, 1.57, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('model/newbook.glb')
