/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Rectangle(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('model/rectangle.glb')
  const { actions, names } = useAnimations(animations, group)
  useEffect(()=>{
    console.log(actions, names);
    actions.animation_0.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-470.79, 16.19, -9.23]} />
      </group>
    </group>
  )
}

useGLTF.preload('model/rectangle.glb')
