/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Spoon(props) {
  const { nodes, materials } = useGLTF('model/spoon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Extrude.geometry} material={materials['Metal Set 01']} position={[0.07, 0, 0.34]} />
    </group>
  )
}

useGLTF.preload('model/spoon.glb')
