/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Arte Hexe (https://sketchfab.com/illusive_skarwing)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tablet-folder-43976803a2b141c6b467408bda6f2ef7
title: Tablet folder
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TableFolder(props) {
  const { nodes, materials } = useGLTF('model/tablet_folder.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 1.48]}>
            <group position={[-13.59, 0.56, -1.1]}>
              <mesh geometry={nodes.StackOfPaper_blinn2_0.geometry} material={materials.blinn2} />
            </group>
            <group position={[0, 0, -1.48]}>
              <mesh geometry={nodes.Pen_blinn2_0.geometry} material={materials.blinn2} />
            </group>
            <group position={[0, 0, -1.48]}>
              <mesh geometry={nodes.Tablet_blinn2_0.geometry} material={materials.blinn2} />
            </group>
            <group position={[0, 0, -1.48]}>
              <mesh geometry={nodes.Paper_blinn2_0.geometry} material={materials.blinn2} />
            </group>
            <group position={[0, 0, -1.48]}>
              <mesh geometry={nodes.Pin_blinn2_0.geometry} material={materials.blinn2} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('model/tablet_folder.glb')
