/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tear(props) {
  const { nodes, materials } = useGLTF('model/tear.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Subdivision_Surface1.geometry} material={materials['Mat.1']} position={[0, 2.75, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('model/tear.glb')
