/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: o500094112 (https://sketchfab.com/o500094112)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/travel-bag-f9b7be8237b94ac0aa0f042c462cd864
title: Travel Bag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TravelBag(props) {
  const { nodes, materials } = useGLTF('model/travel_bag.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.18, -209.75, 54.65]} rotation={[-Math.PI / 2, 0, 0]} scale={[11.62, 11.62, 22.57]}>
            <mesh geometry={nodes.Cube004_Material008_0.geometry} material={materials['Material.008']} />
          </group>
          <group position={[0, 331.2, -97.01]} rotation={[-Math.PI / 2, 0, 0]} scale={[85.77, 104.96, 104.96]}>
            <mesh geometry={nodes.Cube003_Material005_0.geometry} material={materials['Material.005']} />
          </group>
          <group position={[0, -6.39, -41.26]} rotation={[-Math.PI / 2, 0, 0]} scale={[98.9, 58.22, 97.75]}>
            <mesh geometry={nodes.Cube002_Material006_0.geometry} material={materials['Material.006']} />
          </group>
          <group position={[0, -8.4, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0, 8.22, -6.44]} rotation={[-Math.PI / 2, 0, 0]} scale={94.9}>
            <mesh geometry={nodes.Cube001_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube001_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-0.72, -184.25, -47.66]} rotation={[-Math.PI / 2, 0, 0]} scale={11.06}>
            <mesh geometry={nodes.Cube014_Material014_0.geometry} material={materials['Material.014']} />
            <mesh geometry={nodes.Cube014_Material014_0_1.geometry} material={materials['Material.014']} />
          </group>
          <group position={[-0.97, -213.88, -47.89]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[18.49, 18.49, 8.82]}>
            <mesh geometry={nodes.Cylinder006_Material007_0.geometry} material={materials['Material.007']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('model/travel_bag.glb')
