/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Work(props) {
  const { nodes, materials } = useGLTF('model/work.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Building_29.geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('model/work.glb')
